### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by valery-nguyen** [valery-nguyen/somethingSpecial#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by valery-nguyen** [comment]
All checked and ready for review!

**Comment by andywynkoop** [comment]
Hey Valery, looking good so far! Here are a few minor changes that I think you should make:
- [ ] Hitting 'Enter' when filling out the Sign In form toggles the show/hide password button, it should instead try to submit the form
- [ ] If I try to sign in with a correct email but invalid password I see the message "We don't have that email on file" - a different error message should display for invalid password (or both could say something like invalid credentials)
- [ ] A lot of the page looks about 10% smaller than it needs to be (especially the logo, search box, checkout cart, etc.) - make sure that you have both your site and the original site at a view of 100% when matching styling

**Comment by valery-nguyen** [comment]
Hi, I've corrected all 3 points. For the last bulletpoint, I mainly focused on the top portion of the page, including all elements that you listed and more.
